export const CAROUSEL_UPDATE = "CAROUSEL_UPDATE";

export const LOAD_IMAGES_REQUEST = "LOAD_IMAGES_REQUEST";
export const LOAD_IMAGES_SUCCESS = "LOAD_IMAGES_SUCCESS";
export const LOAD_IMAGES_FAIL = "LOAD_IMAGES_FAIL";
